### ISSUE TITLE
Enable squash merging and set it as default

### ISSUE THREAD

**Issue by plata** [flathub/org.kde.kalm#13]
I can only do a "plain" merge and the commit message is in the form "Merge branch 'master' into". I would like to use squash merge with the commit message defaulting to the PR title.

Please also enable auto merge (also for org.kde.telly-skout).

**Comment by travier** [comment]
You need to ask that in https://github.com/flathub/flathub/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

**Comment by plata** [comment]
https://github.com/flathub/flathub/issues/5931
